#!/usr/bin/env sh
# ─────────────────────────────────────────────────────────────────────────
# Sync git identity to your GitHub account.
#
# THE PROBLEM
#   On Coder, the agent injects GIT_AUTHOR_EMAIL / GIT_COMMITTER_EMAIL from your
#   Coder *profile* email (e.g. you@probabilitydrive.com). Environment
#   variables beat `git config`, so they win for every commit. When that
#   profile address is not a verified email on your GitHub account, GitHub and
#   Vercel can't attribute the commit ("commit author email is not valid") and
#   block the build.
#
# THE FIX
#   Derive your real GitHub identity via `gh` and persist it so git uses it:
#     • ~/.config/git/identity.env     sourced by ~/.zshenv to OVERRIDE the
#                                      Coder-injected GIT_*_EMAIL vars (the only
#                                      thing that actually wins inside a shell).
#     • ~/.config/git/identity.config  an [include] in ~/.gitconfig, for tools
#                                      that read git config and for non-Coder
#                                      machines.
#
# Email preference: your primary *verified* GitHub email, else the privacy-safe
# {id}+{login}@users.noreply.github.com (always attributable, never leaks a
# personal address). Override anything here by setting [user] in
# ~/.config/git/local.config (it is included last, so it wins).
#
# Best-effort and offline-safe: if `gh` is missing or unauthenticated this
# no-ops and leaves whatever identity Coder provided. Safe to re-run.
# ─────────────────────────────────────────────────────────────────────────
set -u

cfg_dir="${XDG_CONFIG_HOME:-$HOME/.config}/git"
env_file="$cfg_dir/identity.env"
inc_file="$cfg_dir/identity.config"

# Single-quote a value for safe sourcing in POSIX sh (handles spaces, etc.).
sq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

command -v gh >/dev/null 2>&1 || exit 0

# One call for the public profile; TSV survives spaces in the display name.
ident="$(gh api user --jq '[(.login), (.id|tostring), (.name // .login)] | @tsv' 2>/dev/null)" || exit 0
[ -n "$ident" ] || exit 0
login="$(printf '%s' "$ident" | cut -f1)"
id="$(printf '%s' "$ident" | cut -f2)"
name="$(printf '%s' "$ident" | cut -f3)"
[ -n "$login" ] && [ -n "$id" ] || exit 0

# Prefer the primary verified GitHub email; fall back to the noreply address.
email="$(gh api user/emails --jq 'map(select(.verified and .primary))[0].email // empty' 2>/dev/null)"
[ -n "$email" ] || email="${id}+${login}@users.noreply.github.com"

mkdir -p "$cfg_dir"

# Shell env override (wins over the Coder-injected GIT_*_EMAIL).
{
  printf '# Auto-generated by sync-identity.sh. Do not edit; override in local.config.\n'
  printf 'export GIT_AUTHOR_NAME=%s\n'     "$(sq "$name")"
  printf 'export GIT_AUTHOR_EMAIL=%s\n'    "$(sq "$email")"
  printf 'export GIT_COMMITTER_NAME=%s\n'  "$(sq "$name")"
  printf 'export GIT_COMMITTER_EMAIL=%s\n' "$(sq "$email")"
} > "$env_file"

# git-config include (for IDEs/tools that read config and non-Coder machines).
{
  printf '# Auto-generated by sync-identity.sh. Do not edit; override in local.config.\n'
  printf '[user]\n'
  printf '\tname = %s\n'  "$name"
  printf '\temail = %s\n' "$email"
} > "$inc_file"

printf 'git identity → %s <%s>\n' "$name" "$email"
